POST http://localhost:3000/user HTTP/1.1
content-type: application/json

{
    "name": "Priscilla Demoner",
    "email": "priscillanara@hotmail.com",
    "password": "Abc@12345",
    "sss": "admin"
}
###
GET http://localhost:3000/user HTTP/1.1

###
POST http://localhost:3000/auth HTTP/1.1
Content-Type: application/json

{
    "email": "priscillanara@hotmail.com",
    "password": "Abc@12345"
}