# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI
on:
  push:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['4.4']
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - run: npm ci
    
    - run: npm run test

  build:
    needs: test
    runs-on: self-hosted
    environment: production
    
    env:
      NODE_ENV: production
      HOST: 0.0.0.0
      DB_AUTH_SOURCE: ${{ secrets.DB_AUTH_SOURCE }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      JWT_AUTH_SECRET: ${{ secrets.JWT_AUTH_SECRET }}

    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: create env file
      run: |
        touch .env
        echo NODE_ENV=$NODE_ENV >> .env
        echo HOST=$HOST >> .env
        echo DB_AUTH_SOURCE=$DB_AUTH_SOURCE >> .env
        echo DB_USER=$DB_USER >> .env
        echo DB_PASS=$DB_PASS >> .env
        echo JWT_AUTH_SECRET=$JWT_AUTH_SECRET >> .env
        
    - run: npm ci
    - run: pm2 restart CMPaaS
